
package com.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://pkg/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://pkg/", className = "com.wsclient.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://pkg/", className = "com.wsclient.AddResponse")
    @Action(input = "http://pkg/HelloWorld/addRequest", output = "http://pkg/HelloWorld/addResponse")
    public String add(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param value2
     * @param value1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplynumber", targetNamespace = "http://pkg/", className = "com.wsclient.Multiplynumber")
    @ResponseWrapper(localName = "multiplynumberResponse", targetNamespace = "http://pkg/", className = "com.wsclient.MultiplynumberResponse")
    @Action(input = "http://pkg/HelloWorld/multiplynumberRequest", output = "http://pkg/HelloWorld/multiplynumberResponse")
    public int multiplynumber(
        @WebParam(name = "value1", targetNamespace = "")
        int value1,
        @WebParam(name = "value2", targetNamespace = "")
        int value2);

    /**
     * 
     * @param value2
     * @param value1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addnumber", targetNamespace = "http://pkg/", className = "com.wsclient.Addnumber")
    @ResponseWrapper(localName = "addnumberResponse", targetNamespace = "http://pkg/", className = "com.wsclient.AddnumberResponse")
    @Action(input = "http://pkg/HelloWorld/addnumberRequest", output = "http://pkg/HelloWorld/addnumberResponse")
    public int addnumber(
        @WebParam(name = "value1", targetNamespace = "")
        int value1,
        @WebParam(name = "value2", targetNamespace = "")
        int value2);

    /**
     * 
     * @param value2
     * @param value1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "restnumber", targetNamespace = "http://pkg/", className = "com.wsclient.Restnumber")
    @ResponseWrapper(localName = "restnumberResponse", targetNamespace = "http://pkg/", className = "com.wsclient.RestnumberResponse")
    @Action(input = "http://pkg/HelloWorld/restnumberRequest", output = "http://pkg/HelloWorld/restnumberResponse")
    public int restnumber(
        @WebParam(name = "value1", targetNamespace = "")
        int value1,
        @WebParam(name = "value2", targetNamespace = "")
        int value2);

    /**
     * 
     * @param value2
     * @param value1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dividenumber", targetNamespace = "http://pkg/", className = "com.wsclient.Dividenumber")
    @ResponseWrapper(localName = "dividenumberResponse", targetNamespace = "http://pkg/", className = "com.wsclient.DividenumberResponse")
    @Action(input = "http://pkg/HelloWorld/dividenumberRequest", output = "http://pkg/HelloWorld/dividenumberResponse")
    public int dividenumber(
        @WebParam(name = "value1", targetNamespace = "")
        int value1,
        @WebParam(name = "value2", targetNamespace = "")
        int value2);

}
